### ISSUE TITLE
SWO on BMP

### ISSUE THREAD

**Issue by koendv** [sidprice/vgdb_semihosting_test#1]
Hi.

Pardon me for dropping in like this. I'm a bmp user. bmp is nice design, cheap and cheerful, and has the advantage that you don't need to run a separate gdb server program. However, to fully use bmp you still need a SWO viewer. I'd like to do away with that. I've written a patch that does the swo decoding in the black magic probe itself. The decoded swo stream is written to the bmp usb serial. To see the swo stream on Windows, you just connect PuTTY the usb serial port; on linux you just type "cat /dev/ttyBmpTarg". No special program needed. The patch simply adds a "decode" argument to the "monitor traceswo" command. e.g.:
"monitor traceswo decode" will decode the full swo stream and print it to the usb serial port.
"monitor traceswo decode 0 2" will print only swo channels 0 and 2.
On a bmp with asynchronous swo, you have to add the baud rate, e.g. "monitor 2250000 traceswo decode"
Without the "decode" argument the traceswo stream is written to the trace port, as usual.
I've tested this patch on a STM32F103 bmp, with asynchronous swo, and it works fine. I haven't tested STM32F401 with Manchester coding. Could you take a look and tell me your opinion? Thanks.

regards,

koen

[blackmagic-traceswo-patch3.txt](https://github.com/sidprice/vgdb_semihosting_test/files/4613990/blackmagic-traceswo-patch3.txt)

**Comment by sidprice** [comment]
I don't know why this is here, this is not the Blackmagic Probe repository. That is at https://github.com/blacksphere/blackmagic

**Comment by koendv** [comment]
ok. Well, I read your blog and it seemed we had similar interests. It's just that I'd like to hear a second opinion about this patch to decode traceswo, to see whether it works with manchester encoding, before doing a pull request at the bmp git.
